package com.example.bloodpressureapplication.ui.theme
import androidx.compose.ui.graphics.Color


val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)
val red = Color(0xFFBA1926)
val redScaffold = Color(0xFFc70e1d)
val gray = Color(0xFFf0eded)

// val md_theme_light_primary = Color(0xFFBA1926)
// val md_theme_light_onPrimary = Color(0xFFFFFFFF)
// val md_theme_light_primaryContainer = Color(0xFFFFDAD7)
// val md_theme_light_onPrimaryContainer = Color(0xFF410004)
// val md_theme_light_secondary = Color(0xFFB91934)
// val md_theme_light_onSecondary = Color(0xFFFFFFFF)
// val md_theme_light_secondaryContainer = Color(0xFFFFDAD9)
// val md_theme_light_onSecondaryContainer = Color(0xFF40000A)
// val md_theme_light_tertiary = Color(0xFFB22839)
// val md_theme_light_onTertiary = Color(0xFFFFFFFF)
// val md_theme_light_tertiaryContainer = Color(0xFFFFDAD9)
// val md_theme_light_onTertiaryContainer = Color(0xFF40000A)
// val md_theme_light_error = Color(0xFFBA1A1A)
// val md_theme_light_errorContainer = Color(0xFFFFDAD6)
// val md_theme_light_onError = Color(0xFFFFFFFF)
// val md_theme_light_onErrorContainer = Color(0xFF410002)
// val md_theme_light_background = Color(0xFFFFFBFF)
// val md_theme_light_onBackground = Color(0xFF410005)
// val md_theme_light_surface = Color(0xFFFFFBFF)
// val md_theme_light_onSurface = Color(0xFF410005)
// val md_theme_light_surfaceVariant = Color(0xFFF5DDDB)
// val md_theme_light_onSurfaceVariant = Color(0xFF534342)
// val md_theme_light_outline = Color(0xFF857371)
// val md_theme_light_inverseOnSurface = Color(0xFFFFEDEB)
// val md_theme_light_inverseSurface = Color(0xFF5F1416)
// val md_theme_light_inversePrimary = Color(0xFFFFB3AE)
// val md_theme_light_shadow = Color(0xFF000000)
// val md_theme_light_surfaceTint = Color(0xFFBA1926)
// val md_theme_light_outlineVariant = Color(0xFFD8C2C0)
// val md_theme_light_scrim = Color(0xFF000000)
//
// val md_theme_dark_primary = Color(0xFFFFB3AE)
// val md_theme_dark_onPrimary = Color(0xFF68000C)
// val md_theme_dark_primaryContainer = Color(0xFF930015)
// val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD7)
// val md_theme_dark_secondary = Color(0xFFFFB3B3)
// val md_theme_dark_onSecondary = Color(0xFF680016)
// val md_theme_dark_secondaryContainer = Color(0xFF920023)
// val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD9)
// val md_theme_dark_tertiary = Color(0xFFFFB3B4)
// val md_theme_dark_onTertiary = Color(0xFF680016)
// val md_theme_dark_tertiaryContainer = Color(0xFF900824)
// val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD9)
// val md_theme_dark_error = Color(0xFFFFB4AB)
// val md_theme_dark_errorContainer = Color(0xFF93000A)
// val md_theme_dark_onError = Color(0xFF690005)
// val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
// val md_theme_dark_background = Color(0xFF410005)
// val md_theme_dark_onBackground = Color(0xFFFFDAD7)
// val md_theme_dark_surface = Color(0xFF410005)
// val md_theme_dark_onSurface = Color(0xFFFFDAD7)
// val md_theme_dark_surfaceVariant = Color(0xFF534342)
// val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2C0)
// val md_theme_dark_outline = Color(0xFFA08C8B)
// val md_theme_dark_inverseOnSurface = Color(0xFF410005)
// val md_theme_dark_inverseSurface = Color(0xFFFFDAD7)
// val md_theme_dark_inversePrimary = Color(0xFFBA1926)
// val md_theme_dark_shadow = Color(0xFF000000)
// val md_theme_dark_surfaceTint = Color(0xFFFFB3AE)
// val md_theme_dark_outlineVariant = Color(0xFF534342)
// val md_theme_dark_scrim = Color(0xFF000000)
//
//
// val seed = Color(0xFFA40019)
// val CustomColor1 = Color(0xFFC3002F)
// val light_CustomColor1 = Color(0xFFBF002E)
// val light_onCustomColor1 = Color(0xFFFFFFFF)
// val light_CustomColor1Container = Color(0xFFFFDAD9)
// val light_onCustomColor1Container = Color(0xFF400009)
// val dark_CustomColor1 = Color(0xFFFFB3B3)
// val dark_onCustomColor1 = Color(0xFF680014)
// val dark_CustomColor1Container = Color(0xFF920021)
// val dark_onCustomColor1Container = Color(0xFFFFDAD)