package com.example.bloodpressureapplication.util

sealed class Screens(val route: String) {
    object SplashScreen : Screens("splash_screen")
    object LoginScreen : Screens("login_screen")
    object SignUpScreen : Screens("signup_screen")
    object ProfileScreen : Screens("profile_screen")
    object HomeScreen : Screens("home_screen")
    object TrackScreen : Screens("track_screen")
    object MeasureScreen : Screens("measure_screen")
    object InfoScreen : Screens("info_screen")
    object MeasureBloodPressureScreen : Screens("blood_pressure_measure_screen")
    object MeasureHeartRateScreen : Screens("heart_rate_measure_screen")
    object ProfileEditScreen : Screens("profile_edit_screen")
    object RemindersScreen : Screens("reminders_screen")
    object EditBloodPressureScreen : Screens("edit_blood_pressure_screen")
    object EditHeartRateScreen : Screens("edit_heart_rate_screen")
    object WhatIsBPScreen : Screens("what_is_bp_screen")
    object BPNumbersScreen : Screens("bp_numbers_screen")
    object ControlBPScreen : Screens("control_bp_screen")
    object BPMythsScreen : Screens("bp_myths_screen")
    object WhatIsHyperScreen : Screens("what_is_hyper_screen")
    object WhatIsHypoScreen : Screens("what_is_hypo_screen")
    object PreventHyperScreen : Screens("prevent_hyper_screen")
    object PreventHypoScreen : Screens("prevent_hypo_screen")
    object WhatIsHRScreen :Screens("what_is_hr_screen")
    object HRNumbersScreen :Screens("hr_numbers_screen")
    object HRFactorsScreen :Screens("hr_factors_screen")
    object HRComplicationsScreen :Screens("hr_complications_screen")

}
